### ISSUE TITLE
Bad management of relative volume

### ISSUE THREAD

**Issue by jibeer** [nohum/chromecast-mqtt-connector#1]
In handler/properties.py, line 185, should be
is_relative = payload[0] == "-" or payload[**0**] == "+"
instead of 
is_relative = payload[0] == "-" or payload[**1**] == "+"

**Comment by jibeer** [comment]
In handler/properties.py
The test range (0-100) looses the relative sign !

Should have something like 
        **if is_relative == 0:**
            if value > 100:
                value = 100
            elif value < 0:
                value = 0

**Comment by nohum** [comment]
Thank you for reporting! I am sorry, I haven't got a notification about your issue. Nevertheless, I have fixed both issues!
