### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Odianosen25** [nohum/chromecast-mqtt-connector#13]
Hello,

Please I don't understand how to use your code?

Can you kindly tell me what and what I need to do?

regards

**Comment by nohum** [comment]
Hi!

First, you have to clone or download the repo to your local machine. Change to the root of the downloaded repo (where requirements.txt is located). Execute `pip3 install -r requirements.txt` (assuming that you have pip for python 3 already installed). If you have some special MQTT configuration, copy the file `config.ini.dist` to `config.ini` and change the MQTT settings to your needs.

Finally, you can start the software by executing the `connector.py` on a shell prompt.

**Comment by Odianosen25** [comment]
@nohum, 

Many thanks for the time to explain. 

Kind regards
