### ISSUE TITLE
 ImportError: cannot import name 'get_chromecast'

### ISSUE THREAD

**Issue by sbolten** [nohum/chromecast-mqtt-connector#4]
When trying to call connector.py I get the following error:
```

Traceback (most recent call last):
  File "./connector.py", line 4, in <module>
    from handler.event import EventHandler
  File "/home/stephan/chromecast_mqtt/chromecast-mqtt-connector/handler/event.py", line 1, in <module>
    from handler.adapter import ChromecastConnection, ChromecastConnectionCallback
  File "/home/stephan/chromecast_mqtt/chromecast-mqtt-connector/handler/adapter.py", line 2, in <module>
    from pychromecast import get_chromecast, ChromecastConnectionError, IDLE_APP_ID
ImportError: cannot import name 'get_chromecast'

```
Output of pip3 freeze:

```
enum-compat==0.0.2
netifaces==0.10.4
numpy==1.8.2
paho-mqtt==1.2.1
Pillow==2.6.1
protobuf==3.2.0
PyChromecast==0.8.1
requests==2.13.0
RTIMULib==7.2.1
sense-hat==2.2.0
six==1.10.0
zeroconf==0.19.0
```
Problematic line seems to be:

`from handler.event import EventHandler`

Since I am not a python guy I have no clue how to fix it.

Regards,

Stephan

**Comment by nohum** [comment]
Hello!

Thanks for reporting, the PyChromecast library has been updated, so for the moment your PyChromecast installation is _too new_. 

You can fix this for the moment being by uninstalling PyChromecast and installing a working specific version like so:

```
pip3 install PyChromecast==0.7.7
```

Thanks for reporting, I will look into that.

**Comment by nohum** [comment]
Actually, I fixed the problem in the branch [#4-fix-old-pychromecast](https://github.com/nohum/chromecast-mqtt-connector/tree/%234-fix-old-pychromecast) if you want to try it out without needing to downgrade anything.

**Comment by sbolten** [comment]
Found the problem - had to install an older version of pychromecast --> 0.7.7. All versions above do not have the get_chromecast thing.....

sudo pip3 install pychromecast==0.7.7

Anyhow the chromecast-mqtt-connector progs should be able to run against the latest version of pychromecast.

Stephan

**Comment by nohum** [comment]
@sbolten See the two comments and the branch above ;)

**Comment by sbolten** [comment]
Seems that I found the "bug" while you fixed it - thank anyway... :-)

Will try your fix later. Thx again - great support.

**Comment by sbolten** [comment]
Works like a charm with the fix branch.....
